name: Bug Report
description: Found a bug in RADIOD?
title: "[Bug]: "
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: input
  id: version
  attributes:
    label: Version of RADIOD
    description: Fill in below what version of RADIOD you are using, including your OS.
    placeholder: ex. v1.6.0
  validations:
    required: true
- type: textarea
  id: expected
  attributes:
    label: Expected result
    description: Describe in a few words what you expected to happen.
  validations:
    required: true
- type: textarea
  id: actual
  attributes:
    label: Actual result
    description: Describe in a few words what actually happens.
  validations:
    required: true
- type: textarea
  id: reproduce
  attributes:
    label: Steps to reproduce
    description: As detailed as possible, please tell us how we can reproduce this. Feel free to attach screenshots or logs to make it more clear.
    placeholder: |
      1. Publish an entry
      2. Wait for RADIOD to refresh entrys
      3. Entry doesnt get published.
  validations:
    required: true
